ODPR-1651[AK]- Added user Allowlist
hmrc/digital-platform-reporting-manage-frontend pull request #36
Opened 2024-10-29 12:04 UTC by AKKUM

2024-10-29 14:40 UTC, georgievh commented
I think this change is braking the journey tests. We need to make sure the journey tests can still pass after this change.

2024-10-29 14:40 UTC, georgievh requested changes

2024-10-29 14:40 UTC, georgievh commented on test/controllers/actions/AuthActionSpec.scala
> +
Empty line not needed. Also the file has a few warnings that we could address.

2024-10-30 13:47 UTC, jassalrichy approved these changes

2024-10-30 14:36 UTC, georgievh approved these changes

2024-10-30 14:38 UTC, merged